# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20171213_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='get_desc', serialize=False, to='courses.Course'),
        ),
    ]
