# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20171213_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
    ]
