# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='course',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
